name: Feature request
description: Suggest an idea for this project
title: "[FEAT]: <TITLE>"
labels: ["enhancement"]
assignees:
  - DrKJeff16
body:
  - type: checkboxes
    attributes:
      label: Did you check the docs and looked for existing issues?
      description: Tick all the checkboxes below to validate your issue
      options:
        - label: I have checked for existing issues related to this one, whether open or closed
          required: true
        - label: I have checked for existing PRs and none address this, whether open or closed
          required: true
  - type: textarea
    attributes:
      label: What suggestion do you have?
      description: Write down, as detailed as you can, about your suggestion
    validations:
      required: true
  - type: textarea
    attributes:
      label: How would this project improve?
      description: Describe clearly how would this project benefit from your suggestion
    validations:
      required: true
  - type: textarea
    attributes:
      label: Have you considered alternative solutions?
      description: Please describe any alternative solutions you have considered, if applicable
    validations:
      required: false
  - type: input
    attributes:
      label: "What's the text editor you're using?"
      placeholder: "nvim|vscode|..."
    validations:
      required: false
  - type: input
    attributes:
      label: "What version of WezTerm are you using? (`wezterm --version`)"
      placeholder: wezterm 20250725-073938-dd6e5bd2
    validations:
      required: false
  - type: input
    attributes:
      label: "Operating System and, if possible, what version?"
      placeholder: Arch Linux 6.15.6-arch1-1
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: If there's more info you could tell, please do. Screenshots too, if applicable
    validations:
      required: false
