name: Greetings
on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
jobs:
  greet:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ### Automated Greeting

            Thank you for your feedback!

            Your issue will be adressed **ASAP**.
          pr-message: |
            ### Automated Greeting

            Many many thanks for your contributions!

            Your PR will be checked **ASAP**.
