name: panvimdoc
on:
  push:
    paths:
      - .github/workflows/panvimdoc_plugins.yml
      - docs/*.md
  workflow_dispatch:
permissions:
  contents: write
jobs:
  plugins:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc (plugins)
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run panvimdoc for ai-commander.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-ai-commander
          description: "`ai-commander` types"
          pandoc: docs/ai-commander.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for ai-helper.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-ai-helper
          description: "`ai-helper` types"
          pandoc: docs/ai-helper.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for bar_wezterm.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-bar_wezterm
          description: "`bar_wezterm` types"
          pandoc: docs/bar_wezterm.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for dev-wezterm.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-dev-wezterm
          description: "`dev-wezterm` types"
          pandoc: docs/dev-wezterm.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for lib-wezterm.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-lib-wezterm
          description: "`lib-wezterm` types"
          pandoc: docs/lib-wezterm.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for modal_wezterm.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-modal_wezterm
          description: "`modal_wezterm` types"
          pandoc: docs/modal_wezterm.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for pinned-tabs.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-pinned-tabs
          description: "`pinned-tabs` types"
          pandoc: docs/pinned-tabs.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for pivot_panes.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-pivot_panes
          description: "`pivot_panes` types"
          pandoc: docs/pivot_panes.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for presentation_wez.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-presentation_wez
          description: "`presentation_wez` types"
          pandoc: docs/presentation_wez.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for quick_domains.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-quick_domains
          description: "`quick_domains` types"
          pandoc: docs/quick_domains.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for resurrect.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-resurrect
          description: "`resurrect` types"
          pandoc: docs/resurrect.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for rosepine.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-rosepine
          description: "`rosepine` types"
          pandoc: docs/rosepine.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for sessionizer.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-sessionizer
          description: "`sessionizer` types"
          pandoc: docs/sessionizer.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for smart-splits.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-smart-splits
          description: "`smart-splits` types"
          pandoc: docs/smart-splits.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for smart_workspace_switcher.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-smart_workspace_switcher
          description: "`smart_workspace_switcher` types"
          pandoc: docs/smart_workspace_switcher.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for stack-wez.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-stack-wez
          description: "`stack-wez` types"
          pandoc: docs/stack-wez.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for tabline_wez.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-tabline_wez
          description: "`tabline_wez` types"
          pandoc: docs/tabline_wez.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wez-pain-control.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-wez-pain-control
          description: "`wez-pain-control` types"
          pandoc: docs/wez-pain-control.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wez-tmux.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-wez-tmux
          description: "`wez-tmux` types"
          pandoc: docs/wez-tmux.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-config.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-wezterm-config
          description: "`wezterm-config` types"
          pandoc: docs/wezterm-config.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-theme-rotator.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-wezterm-theme-rotator
          description: "`wezterm-theme-rotator` types"
          pandoc: docs/wezterm-theme-rotator.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for workspace-picker.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-workspace-picker
          description: "`workspace-picker` types"
          pandoc: docs/workspace-picker.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Auto-Commit
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}
